aulianza/aulianza.id

src/common/components/elements/CommandPalette.tsx

fix: update transition as fragment

---

package.json
src/common/components/elements/Status.tsx
src/common/components/elements/ThemeToggleButton.tsx
src/common/components/layouts/index.tsx
src/common/components/layouts/partials/Copyright.tsx
src/common/components/layouts/partials/Sidebar.tsx
src/common/components/sidebar/MenuItem.tsx
src/common/components/sidebar/MobileMenu.tsx
src/common/components/sidebar/MobileMenuButton.tsx
src/common/components/sidebar/Profile.tsx
src/common/components/sidebar/ProfileHeader.tsx
src/common/styles/globals.css
yarn.lock

feat: add theme toggle button

---

src/common/components/sidebar/Profile.tsx

fix: set header fixed on mobile

---

src/common/components/elements/CommandPalette.tsx
src/common/components/sidebar/MobileMenuButton.tsx
src/modules/home/components/Introduction.tsx
src/modules/home/components/Services.tsx

fix: improve some stuff

---

README.md
src/modules/home/components/Introduction.tsx

fix: update introduction

---

src/common/components/elements/CommandPalette.tsx
src/common/components/sidebar/MenuItem.tsx
src/common/components/sidebar/Navigation.tsx
src/common/constant/menu.tsx
src/common/types/menu.ts

feat: add command pallete with google search

---

.env.example
package.json
src/common/components/elements/CommandPalette.tsx
src/common/components/sidebar/Navigation.tsx
src/pages/api/chat.ts
src/services/chatgpt.ts
yarn.lock

Integrate command with chatGPT

---

src/pages/api/chat.ts

fix: remove custom headers

---

vercel.json

feat: add vercel.json

---

vercel.json

fix: vercel.json

---

src/common/components/elements/CommandPalette.tsx

fix: add dynamic cmd title

---

README.md
package.json
src/common/components/elements/CommandPalette.tsx
src/pages/api/chat.ts
src/services/chatgpt.ts
yarn.lock

Ehnance & Move AI Service

---

src/pages/api/chat.ts

fix: next api header error

---

src/services/chatgpt.ts

ChatGPT: add max_tokens

---

src/pages/api/chat.ts
src/services/chatgpt.ts

Update GPT AI Model from Chat Completions to Completions

---

src/common/components/elements/CommandPalette.tsx
src/modules/cmdpallete/components/AiLoading.tsx
src/modules/cmdpallete/components/AiResponses.tsx
src/modules/cmdpallete/components/QueryNotFound.tsx

Split cmd component into smaller

---

src/services/chatgpt.ts

Update openai engine model to text-davinci-003

---

src/services/chatgpt.ts

fix: upgrade max_tokens from 100 to 200

---

src/services/chatgpt.ts

fix: update prompt

---

src/services/chatgpt.ts

fix: update ai engine model

---

src/common/constant/about.ts

fix: update a story

---

src/common/components/sidebar/Navigation.tsx
tailwind.config.js

feat: add badge animation

---

src/common/components/elements/Button.tsx
src/common/components/elements/PageHeading.tsx
src/common/components/elements/SectionHeading.tsx
src/common/components/elements/Status.tsx
src/common/components/elements/Tooltip.tsx
src/common/components/layouts/partials/Copyright.tsx
src/common/components/sidebar/Menu.tsx
src/common/components/sidebar/Navigation.tsx
src/common/components/sidebar/ProfileHeader.tsx
src/common/constant/menu.tsx
src/common/styles/fonts.ts
src/modules/blog/components/BlogListHeader.tsx
src/modules/home/components/BlogPreview.tsx
src/modules/home/components/Introduction.tsx

Adjust some style

---

src/common/components/elements/ThemeToggleButton.tsx
src/common/components/sidebar/MenuItem.tsx
src/common/components/sidebar/Profile.tsx
src/common/components/sidebar/ProfileHeader.tsx

fix: adjust mobile header

---

src/common/components/sidebar/MenuItem.tsx
src/common/components/sidebar/MobileMenuButton.tsx
src/common/components/sidebar/Profile.tsx

feat: add hamburger menu animation

---

src/common/components/sidebar/MobileMenu.tsx
src/common/components/sidebar/Profile.tsx

fix: adjust mobile menu animation

---

src/common/components/sidebar/MobileMenuButton.tsx
src/common/components/sidebar/Profile.tsx
src/common/components/sidebar/ProfileHeader.tsx

fix: sidebar menu style

---

src/common/components/elements/Card.tsx
src/common/components/elements/Tooltip.tsx
src/common/components/skeleton/BlogCardSkeleton.tsx
src/common/components/skeleton/ProductCardSkeleton.tsx
src/common/constant/stacks.tsx
src/modules/about/components/CareerCard.tsx
src/modules/about/components/Story.tsx
src/modules/blog/components/BlogCard.tsx
src/modules/home/components/Introduction.tsx
src/modules/home/components/Services.tsx
src/modules/projects/components/ProjectCard.tsx
src/modules/projects/components/ProjectDetail.tsx

feat: add project stack icon, update card

---

src/modules/projects/components/ProjectCard.tsx
src/modules/projects/components/ProjectDetail.tsx

fix: project detail card

---

src/common/components/elements/CodeBlock.tsx
src/common/components/elements/ThemeToggleButton.tsx
src/common/components/sidebar/MenuItem.tsx
src/common/constant/menu.tsx
src/common/types/menu.ts
src/modules/about/components/CareerCard.tsx
src/modules/about/components/CareerList.tsx
src/modules/blog/components/ViewOptions.tsx
src/modules/cmdpallete/components/AiResponses.tsx
src/modules/cmdpallete/components/QueryNotFound.tsx
src/modules/contact/components/Contact.tsx
src/modules/home/components/BlogPreview.tsx
src/modules/home/components/Services.tsx
src/modules/projects/components/ProjectCard.tsx
src/modules/projects/components/ProjectDetail.tsx
src/modules/projects/components/ProjectLink.tsx
src/pages/blog/[slug].tsx

feat: integrate event tracker

---

src/common/components/sidebar/MenuItem.tsx

fix: remove menu event tracker

---

src/modules/home/components/BlogPreview.tsx
src/modules/projects/components/ProjectCard.tsx

fix: remove event tracker

---

src/common/components/elements/AnimatedBars.tsx
src/common/components/elements/NowPlayingBar.tsx
src/common/components/elements/NowPlayingCard.tsx
src/common/components/layouts/index.tsx
src/common/components/sidebar/MobileMenu.tsx
src/common/components/sidebar/Profile.tsx
src/common/types/spotify.ts
src/pages/api/now-playing.ts
src/services/spotify.ts

Add Spotify Player

---

src/common/components/elements/NowPlayingCard.tsx

fix: update player z-index

---

src/common/components/elements/AnimatedBars.tsx
src/common/components/elements/DevicePopover.tsx
src/common/components/elements/NowPlayingBar.tsx
src/common/components/elements/NowPlayingCard.tsx
src/common/components/elements/PlayerPopover.tsx
src/common/constant/devices.tsx
src/common/types/spotify.ts
src/pages/api/available-devices.ts
src/services/spotify.ts

Spotify Player Info and Available Devices

---

src/common/components/elements/NowPlayingBar.tsx

fix: spotify device list

---

src/common/components/elements/NowPlayingCard.tsx
src/common/components/elements/PlayerPopover.tsx
src/common/components/sidebar/MobileMenu.tsx

fix: adjust player card font size

---

src/common/components/elements/NowPlayingBar.tsx
src/common/components/layouts/partials/Copyright.tsx
src/common/components/sidebar/Navigation.tsx

fix: adjust some stuff

---

src/common/styles/globals.css

fix: update nprogress height

---

src/common/constant/stacks.tsx

feat: add new stacks

---

src/common/types/projects.ts
src/modules/projects/components/ProjectDetail.tsx

feat: add project detail content

---

src/common/components/elements/CodeBlock.tsx
src/common/components/elements/NowPlayingBar.tsx

fix: codeblock padding and cursor

---

src/common/types/projects.ts
src/modules/projects/components/ProjectCard.tsx
src/pages/projects/index.tsx

feat: add project featured

---

package.json
src/common/components/elements/Breakline.tsx
src/common/components/elements/Button.tsx
src/common/components/elements/CodeBlock.tsx
src/common/components/elements/Container.tsx
src/common/components/elements/SectionHeading.tsx
src/common/components/elements/Tabs.tsx
src/common/components/sidebar/MenuItem.tsx
src/common/constant/about.ts
src/modules/blog/components/BlogList.tsx
src/modules/dashboard/components/Contributions/Contributions.tsx
src/pages/api/projects.ts
src/pages/api/read-stats.ts
src/pages/dashboard.tsx
src/services/blog.ts
src/services/spotify.ts
src/services/wakatime.ts
yarn.lock

fix: eslint warning

---

src/common/components/sidebar/Profile.tsx
src/modules/projects/components/ProjectCard.tsx

fix: update ribbon z-index

---

src/common/types/learn.ts
src/contents/learn/problem-solving/duplicate-encoder.mdx
src/pages/learn/[content]/[slug].tsx
src/pages/learn/[content]/index.tsx

feat: add learn meta tag

---

.github/FUNDING.yml

docs: add FUNDING.yml

---

src/contents/learn/problem-solving/sentence-smasher.mdx

feat: add problem solving content - sentence smasher

---

src/contents/learn/problem-solving/sentence-smasher.mdx

fix: Update sentence-smasher.mdx

---

next-seo.config.js
next.config.js
src/common/types/learn.ts
src/contents/learn/problem-solving/count-by-x.mdx
src/contents/learn/problem-solving/duplicate-encoder.mdx
src/contents/learn/problem-solving/sentence-smasher.mdx
src/modules/blog/components/GiscusComment.tsx
src/pages/blog/[slug].tsx
src/pages/learn/[content]/[slug].tsx
src/pages/learn/[content]/index.tsx
src/pages/projects/[slug].tsx

Update Giscuss Comment and Add Meta Tag SEO

---

next-seo.config.js
src/contents/learn/problem-solving/sentence-smasher.mdx

fix: default seo config

---

next-seo.config.js

fix: seo config

---

.env.example
src/common/types/blog.ts
src/modules/blog/components/BlogCard.tsx
src/modules/blog/components/BlogDetail.tsx
src/modules/blog/components/BlogHeader.tsx
src/modules/blog/components/CommentList.tsx
src/pages/api/blog-view.ts
src/pages/blog/[slug].tsx
src/services/blog.ts

Blog Views Count

---

src/modules/blog/components/BlogCard.tsx
src/modules/blog/components/BlogHeader.tsx

fix:  update blog view count

---

package.json
src/pages/blog/[slug].tsx
src/services/blog.ts
src/services/chatgpt.ts
src/services/fetcher.ts
src/services/github.ts
src/services/spotify.ts
src/services/wakatime.ts
yarn.lock

feat: migrate to axios from fetch

---

package.json
src/common/helpers/index.ts
src/modules/about/components/CareerCard.tsx
src/modules/blog/components/BlogCard.tsx
src/modules/blog/components/BlogHeader.tsx
src/modules/blog/components/CommentItem.tsx
src/modules/dashboard/components/CodingActive/CodingActive.tsx
src/modules/dashboard/components/CodingActive/Overview.tsx
src/modules/learn/components/ContentDetailHeader.tsx
src/services/blog.ts
src/services/spotify.ts
yarn.lock

feat: migrate moment to date-fns

---

src/contents/learn/problem-solving/even-or-odd.mdx

feat: add learn problem-solving content

---

src/modules/blog/components/BlogCard.tsx

fix: update blog-card date gap

---

src/contents/learn/problem-solving/count-by-x.mdx
src/contents/learn/problem-solving/duplicate-encoder.mdx
src/contents/learn/problem-solving/even-or-odd.mdx
src/contents/learn/problem-solving/grasshopper-personalized-message.mdx
src/contents/learn/problem-solving/sentence-smasher.mdx
src/contents/learn/problem-solving/sum-without-highest-and-lowest-number.mdx

fix: content meta image

---

src/modules/contact/components/Contact.tsx

fix: update contact email

---

src/common/components/elements/TopBar.tsx

feat: add topbar link utm track

---

package.json
src/common/components/elements/Button.tsx
src/common/components/layouts/header/HeaderSidebar.tsx
src/common/components/layouts/header/HeaderTop.tsx
src/common/components/layouts/index.tsx
src/common/components/sidebar/MenuItem.tsx
src/common/components/sidebar/Navigation.tsx
src/common/constant/menu.tsx
src/common/types/menu.ts
src/modules/blog/components/BlogDetail.tsx
src/modules/playground/components/CodeEditor.tsx
src/modules/playground/components/ConsoleOutput.tsx
src/modules/playground/components/Playground.tsx
src/modules/playground/index.ts
src/pages/learn/[content]/[slug].tsx
src/pages/playground.tsx
yarn.lock

feat: add playground feature

---

src/common/components/layouts/header/HeaderTop.tsx
src/pages/playground.tsx

fix: playground page padding

---

src/pages/playground.tsx

fix: update playground page title

---

src/modules/playground/components/ConsoleOutput.tsx
src/modules/playground/components/Playground.tsx

fix: console output height

---

src/common/components/layouts/index.tsx

feat: add playground on learn section wide

---

src/common/components/elements/ModalWrapper.tsx
src/modules/playground/components/CodeEditor.tsx
src/modules/playground/components/CodePlayground.tsx
src/modules/playground/components/ConsoleOutput.tsx
src/modules/playground/components/Playground.tsx

JavaScript Playground

---

src/common/constant/menu.tsx
src/modules/playground/components/CodePlayground.tsx

feat: add playground event tracker

---

src/common/components/elements/Status.tsx
src/common/components/layouts/header/HeaderTop.tsx
src/common/components/layouts/index.tsx
src/common/components/layouts/partials/Copyright.tsx
src/common/components/sidebar/Navigation.tsx
src/common/constant/menu.tsx
src/modules/contact/components/Contact.tsx
src/modules/contact/components/ContactForm.tsx
src/pages/api/contact.ts
src/pages/playground.tsx
src/services/contact.ts

refactor: sidebar and contact page

---

.env.example

fix: update env

---

src/common/components/elements/TopBar.tsx
src/common/components/layouts/index.tsx

fix: page header position

---

package.json
src/common/styles/globals.css
src/modules/contact/components/BookACall.tsx
src/modules/contact/components/Contact.tsx
src/modules/contact/components/SocialMediaList.tsx
src/modules/home/components/Introduction.tsx
src/modules/projects/components/ProjectCard.tsx
src/modules/projects/components/Projects.tsx
src/pages/projects/index.tsx
yarn.lock

refactor: projects and contact

---

src/common/components/elements/ButtonNavigation.tsx
src/common/components/elements/NavigationSection.tsx
src/common/components/layouts/header/HeaderTop.tsx
src/common/constant/learn.ts
src/pages/api/content.ts
src/pages/learn/[content]/[slug].tsx

feat: add content bottom navigation

---

src/common/components/elements/ButtonNavigation.tsx

fix: navigation button

---

src/common/components/elements/BackButton.tsx
src/common/components/elements/ButtonNavigation.tsx
src/common/components/elements/NavigationSection.tsx
src/common/components/elements/TopBar.tsx
src/common/components/layouts/header/HeaderTop.tsx
src/contents/learn/js-fundamental/1-introduction.mdx
src/pages/learn/[content]/[slug].tsx

fix: few responsive issue

---

src/common/helpers/index.ts
src/common/styles/globals.css
src/common/types/learn.ts
src/contents/learn/js-fundamental/0-introduction.mdx
src/contents/learn/js-fundamental/1-hello-world.mdx
src/contents/learn/js-fundamental/2-comments.mdx
src/contents/learn/js-fundamental/3-variables.mdx
src/contents/learn/js-fundamental/4-types.mdx
src/contents/learn/js-fundamental/5-typeof.mdx
src/contents/learn/js-fundamental/6-equality.mdx
src/contents/learn/js-fundamental/7-numbers.mdx
src/modules/contact/components/ContactForm.tsx
src/modules/learn/components/ChapterCard.tsx
src/modules/learn/components/ContentList.tsx
src/pages/learn/[content]/index.tsx

refactor: learning module

---

src/contents/learn/js-fundamental/0-introduction.mdx
src/contents/learn/js-fundamental/1-hello-world.mdx
src/contents/learn/js-fundamental/2-comments.mdx
src/contents/learn/js-fundamental/3-variables.mdx
src/contents/learn/js-fundamental/4-types.mdx
src/contents/learn/js-fundamental/5-typeof.mdx
src/contents/learn/js-fundamental/6-equality.mdx
src/contents/learn/js-fundamental/7-numbers.mdx
src/modules/learn/components/ContentDetailHeader.tsx

fix: update js category

---

src/common/components/elements/NavigationSection.tsx
src/common/constant/learn.ts
src/common/helpers/index.ts
src/common/types/learn.ts
src/contents/learn/js-fundamental/10-advanced-operator.mdx
src/contents/learn/js-fundamental/8-basic-operator.mdx
src/contents/learn/js-fundamental/9-math.mdx
src/contents/learn/problem-solving/count-by-x.mdx
src/contents/learn/problem-solving/duplicate-encoder.mdx
src/contents/learn/problem-solving/even-or-odd.mdx
src/contents/learn/problem-solving/grasshopper-personalized-message.mdx
src/contents/learn/problem-solving/sentence-smasher.mdx
src/contents/learn/problem-solving/sum-without-highest-and-lowest-number.mdx
src/modules/learn/components/ChapterCard.tsx
src/modules/learn/components/ContentBody.tsx
src/modules/learn/components/ContentDetail.tsx
src/modules/learn/components/ContentPlayground.tsx
src/modules/learn/components/LearnCard.tsx
src/pages/api/content.ts
src/pages/learn/[content]/[slug].tsx
src/pages/learn/[content]/index.tsx

refactor: learn module

---

src/common/components/elements/ButtonNavigation.tsx
src/common/components/elements/NavigationSection.tsx

fix: navigation condition

---

src/common/components/elements/MDXComponent.tsx
src/modules/learn/components/LearnSubContentItem.tsx

fix: adjust font

---

README.md
src/modules/chat/components/Chat.tsx
src/modules/chat/components/ChatAuth.tsx
src/modules/chat/components/ChatButton.tsx
src/modules/chat/components/ChatInput.tsx
src/modules/chat/components/ChatUserInfo.tsx
src/modules/chat/components/ChatWidgetHeader.tsx

feat: chat event tracker

---

src/modules/chat/components/ChatTime.tsx

fix: chat time in mobile view not showing

---

src/modules/chat/components/ChatAuth.tsx

feat: sso login by google

---

src/common/components/elements/CommandPalette.tsx
src/common/components/elements/TopBar.tsx
src/common/components/layouts/index.tsx
src/common/components/sidebar/MenuItem.tsx
src/common/components/sidebar/Navigation.tsx
src/common/constant/learn.ts
src/common/constant/menu.tsx
src/common/constant/stacks.tsx
src/common/styles/globals.css
src/common/types/menu.ts
src/modules/about/components/CareerList.tsx
src/modules/blog/components/BlogCard.tsx
src/modules/chat/components/ChatButton.tsx
src/modules/contact/components/BookACall.tsx
src/modules/home/components/Home.tsx
src/modules/home/components/Introduction.tsx
src/modules/learn/components/ChapterCard.tsx
tailwind.config.js

Improve Some Stuff

---

src/modules/chat/components/Chat.tsx
src/modules/chat/components/ChatButton.tsx
src/modules/chat/components/ChatItem.tsx
src/modules/chat/components/ChatList.tsx
src/modules/chat/components/ChatWidget.tsx

feat: improve chat component

---

src/common/components/elements/Image.tsx
src/common/types/chat.ts
src/modules/chat/components/Chat.tsx
src/modules/chat/components/ChatItem.tsx
src/modules/chat/components/ChatList.tsx
src/modules/contact/components/ContactForm.tsx
src/modules/dashboard/components/CodingActive/Progress.tsx
src/pages/chat.tsx

feat: chat deletion

---

src/modules/chat/components/Chat.tsx
src/modules/chat/components/ChatInput.tsx
src/modules/chat/components/ChatItem.tsx
src/modules/chat/components/ChatUserInfo.tsx
src/pages/chat.tsx

feat: improve chat input

---

src/modules/chat/components/ChatAuth.tsx

fix: minor space y

---

src/common/components/layouts/index.tsx
src/modules/chat/components/ChatWidgetHeader.tsx

fix: guestbook action button

---

src/common/components/layouts/header/HeaderTop.tsx
src/common/components/layouts/index.tsx
src/common/styles/globals.css
src/modules/home/components/Introduction.tsx

fix: topbar appearance

---

src/common/components/elements/InfiniteLoopSlider.tsx
src/common/constant/stacks.tsx
src/modules/about/components/About.tsx
src/modules/about/components/Skills.tsx
src/pages/404.tsx
tailwind.config.js

feat: add skills

---

src/common/constant/about.ts
src/common/styles/globals.css
src/modules/learn/components/LearnCard.tsx

fix: hotfix some typo

---

tailwind.config.js

fix: skills loop speed

---

src/common/components/elements/Status.tsx
src/common/components/elements/TopBar.tsx
src/common/components/layouts/partials/Sidebar.tsx
src/common/components/sidebar/Profile.tsx
src/common/components/sidebar/ProfileHeader.tsx
src/common/styles/globals.css
src/modules/chat/components/ChatAuth.tsx
src/modules/chat/components/ChatButton.tsx
src/modules/chat/components/ChatInput.tsx
src/modules/chat/components/ChatItem.tsx
src/modules/chat/components/ChatWidget.tsx
src/modules/chat/components/ChatWidgetHeader.tsx

fix: refactor some stuff

---

src/common/components/layouts/index.tsx
src/common/constant/careers.ts

fix: update career

---

src/modules/about/components/Resume.tsx

fix: resume url

---

src/common/components/layouts/index.tsx

fix: show topbar

---

.gitignore
src/common/components/elements/NowPlayingBar.tsx
src/common/components/layouts/index.tsx
src/common/components/sidebar/Profile.tsx
src/common/components/skeleton/BlogCardNewSkeleton.tsx
src/common/components/skeleton/BlogFeaturedHeroSkeleton.tsx
src/common/stores/useBlogPageStore.ts
src/common/stores/useChatStore.ts
src/common/types/blog.ts
src/modules/blog/components/BlogCardNew.tsx
src/modules/blog/components/BlogFeaturedHero.tsx
src/modules/blog/components/BlogListNew.tsx
src/pages/blog/[slug].tsx
src/pages/blog/index.tsx

feat: revamp blog list component

---

src/modules/blog/components/BlogCardNew.tsx
src/modules/blog/components/BlogFeaturedHero.tsx
src/modules/blog/components/BlogListNew.tsx
src/modules/home/components/BlogCarousel.tsx
src/modules/home/components/BlogPreview.tsx
src/pages/blog/index.tsx

feat: revamp blog list homepage

---

src/pages/api/views.ts
src/pages/blog/[slug].tsx

fix: blog view count slug

---

src/modules/blog/components/BlogFeaturedSection.tsx
src/pages/api/blog.ts
src/services/blog.ts

feat: add blog filter by category

---

src/common/components/elements/EmptyState.tsx
src/common/components/elements/Pagination.tsx
src/common/components/elements/SearchBar.tsx
src/common/styles/globals.css
src/modules/blog/components/BlogFeaturedSection.tsx
src/modules/blog/components/BlogListNew.tsx
src/pages/api/blog.ts
src/pages/blog/[slug].tsx
src/services/blog.ts

feat: add blog search functionality

---

src/modules/blog/components/BlogListNew.tsx

fix: validate error

---

src/modules/blog/components/BlogListNew.tsx

fix: ipad mini screen ratio on blog

---

src/modules/blog/components/BlogFeaturedHero.tsx
src/modules/blog/components/BlogFeaturedSection.tsx

fix: blog featured condition

---

src/common/components/elements/SkeletonLoader.tsx
src/common/components/skeleton/BlogCardNewSkeleton.tsx
src/common/components/skeleton/BlogFeaturedHeroSkeleton.tsx

fix: skeleton base color

---

src/common/components/elements/MDXComponent.tsx
src/common/components/layouts/index.tsx
src/modules/blog/components/BlogCardNew.tsx
src/modules/blog/components/BlogFeaturedHero.tsx
src/pages/blog/[slug].tsx

fix: console error and warning

---

src/common/constant/careers.ts
src/modules/home/components/Introduction.tsx

fix: update career list

---

next.config.js

feat: add images sources

---

src/__tests__/components/elements/Breakline.test.tsx
src/common/components/elements/Breakline.tsx
src/common/components/elements/SearchBox.tsx
src/common/components/elements/ThemeSwitcher.tsx
src/common/components/layouts/index.tsx
src/common/components/layouts/partials/Sidebar.tsx
src/common/components/sidebar/MenuItem.tsx
src/common/components/sidebar/MobileMenu.tsx
src/common/components/sidebar/Navigation.tsx
src/common/components/sidebar/Profile.tsx
src/common/components/sidebar/ProfileHeader.tsx
src/common/constant/menu.tsx
src/common/styles/globals.css
src/modules/playground/components/PlaygroundHeader.tsx

refactor: sidebar new

---

next.config.js

feat: allow all image url

---

src/common/components/layouts/index.tsx

fix: layout max width

---

src/common/constant/stacks.tsx
src/modules/about/components/About.tsx
src/modules/about/components/Skills.tsx
src/modules/home/components/Home.tsx
src/modules/home/components/SkillsSection.tsx

fix: move skills into homepage

---

.github/workflows/lint.yml

fix: update node version for github actions

---

.github/workflows/lint.yml

fix: update github action @v4

---

.github/workflows/lint.yml

fix: update github actions node version
